### ISSUE TITLE
🥒🥒🥒 Tesztek létrehozása 🥒🥒🥒

### ISSUE THREAD

**Issue by AO7JX4** [E1LX0J/kozlegeny#18]
Összesen 10 Db 🥒 -t hoztam létre a Player/Mechanic/Saboteur osztályok tesztelésére.
Note: Gradle még nemigazán szereti ezeket a teszteket futtatni, ezt még ki kell javitani, de IDE-ben egyesével futtatva müködnek, tehát a syntax/logika az jó.

#17

**Comment by sloweroons** [comment]
🥒 Meglehetősen szép uborkák.

**Comment by E1LX0J** [comment]
Szép munka!
![letöltés](https://github.com/E1LX0J/kozlegeny/assets/127963637/48a3fbc2-8387-426e-b421-4bd0adae1e24)
